# Run command via ssh

name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git pull on DO via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /srv/shiny-server/samplesheet/ && git pull
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: aangelo
          password: ${{ secrets.PASSWORD }}